### ISSUE TITLE
ArrayIndexOutOfBoundsException: 70 when Fields 08090 and 08100 (both optional) are not filled out

### ISSUE THREAD

**Issue by plidauer** [karlkauc/FundsXML-EMT-Converter#9]
Did you even test this piece of software?

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 70
        at org.codehaus.groovy.runtime.dgmimpl.arrays.ObjectArrayGetAtMetaMethod$MyPojoMetaMethodSite.call(ObjectArrayGetAtMetaMethod.java:60)
        at convert$_run_closure4$_closure10$_closure11$_closure13$_closure17$_closure18$_closure19$_closure30$_closure37.doCall(convert.groovy:316)
        at convert$_run_closure4$_closure10$_closure11$_closure13$_closure17$_closure18$_closure19$_closure30$_closure37.doCall(convert.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by karlkauc** [comment]
cannot reproduce the error with my test data. 
could you provide your csv file? with anonymized data?

**Comment by plidauer** [comment]
Erstmal sorry für meine Ausdrucksweise, stehen alle ziemlich unter Druck..

Wir konnten das Problem mit einem Workaround beheben, indem wir im CSV eine 73. Spalte hinzugefügt und bei jeder Zeile den Wert 0 vergeben haben. Wenn die beiden Datumswerte in den letzten beiden Spalten leer gelassen werden, tritt dieser Fehler auf. 

[EMT_2017-12-28 dummy.zip](https://github.com/karlkauc/FundsXML-EMT-Converter/files/1591609/EMT_2017-12-28.dummy.zip)
